### ISSUE TITLE
Cannot write files to directory

### ISSUE THREAD

**Issue by nunocalaim** [upekkha/AppleHardwareTest#24] opened 2016-10-12 10:29 UTC
I try to move the contents to /System/Library/CoreServices/.diagnostics

but it won't allow me to do it even with sudo.
Any thoughts?

**Comment by nunocalaim** [comment] 2016-10-12 11:04
Apparently I need to go into recovery mode and disable something that is there to protect my computer... Is there an easier way?

**Comment by upekkha** [comment] 2016-10-12 12:17
Duplicate of #18, now also explained in the Readme ba982211e8ad4aa4ff99010dc481fb486af78511

**Closed by upekkha** 2016-10-12 12:17 UTC

**Comment by kupietools** [comment] 2019-06-03 00:58
My System Integrity Protection is disabled and it still won't let me copy. Instructions would be preferable to no instructions.
