### ISSUE TITLE
MacBookPro11,1

### ISSUE THREAD

**Issue by frathe** [upekkha/AppleHardwareTest#30] opened 2017-08-12 23:18 UTC
Could somebody provide me the download link for MacBookPro11,1 ("board-id" = <"Mac-189A3D4F975D5FFC">)?

**Comment by 3ji7ja0jb9c** [comment] 2017-09-04 23:59
Close as duplicate of #22.  Find AppleDiagnostics.dmg in 'Install ESD' of recent Mac OS X distribution.

**Closed** 2017-09-05 06:35 UTC
